{
 "title": "Statistical-data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MaxDelay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  maxdelay AS \"最大时延\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    }
   ]
  },
  {
   "title": "Packet Loss Rate - Time series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  meanloss AS \"平均丢包率\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  maxloss AS \"最大丢包率\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    }
   ]
  },
  {
   "title": "Packet Loss Rate - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  meanloss AS \"平均丢包率\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  maxloss AS \"最大丢包率\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    }
   ]
  },
  {
   "title": "MeanDelay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time_date,1s),\n  avg(meandelay) AS \"平均时延\"\nFROM totaldata\nWHERE\n  $__timeFilter(date_time_date)\nGROUP BY 1\nORDER BY $__timeGroup(date_time_date,1s)"
    }
   ]
  },
  {
   "title": "Maximum Link Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "res", "text": "res", "type": "number" }
     ],
     "query_mode": "standard",
     "source": "url",
     "type": "json",
     "url": "http://192.168.1.104:10086/maxrate",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}